// Generated by CoffeeScript 1.4.0
var allowCrossDomain, apiv1Middleware, splash, translate, view;

splash = function(req, res, next) {
  var isStatic, _ref;
  isStatic = req.url.split('/')[1] === 'static';
  if (!((((_ref = req.query) != null ? _ref.play : void 0) != null) || req.getModel().get('_userId') || isStatic)) {
    return res.redirect('/static/front');
  } else {
    return next();
  }
};

view = function(req, res, next) {
  var model;
  model = req.getModel();
  model.set('_mobileDevice', /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(req.header('User-Agent')));
  model.set('_nodeEnv', model.flags.nodeEnv);
  return next();
};

allowCrossDomain = function(req, res, next) {
  res.header("Access-Control-Allow-Origin", req.headers.origin || "*");
  res.header("Access-Control-Allow-Methods", "OPTIONS,GET,POST,PUT,HEAD,DELETE");
  res.header("Access-Control-Allow-Headers", "Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key");
  if (req.method === 'OPTIONS') {
    return res.send(200);
  } else {
    return next();
  }
};

translate = function(req, res, next) {
  var model;
  model = req.getModel();
  return next();
};

apiv1Middleware = function(req, res, next) {
  var _ref;
  if ((_ref = req.habit) == null) {
    req.habit = {};
  }
  return next();
};

module.exports = {
  splash: splash,
  view: view,
  allowCrossDomain: allowCrossDomain,
  translate: translate,
  apiv1Middleware: apiv1Middleware
};
