// Generated by CoffeeScript 1.4.0
var algos, moment;

moment = require('moment');

algos = require('habitrpg-shared/script/algos');

module.exports.app = function(appExports, model) {
  var user;
  user = model.at('_user');
  appExports.emulateNextDay = function() {
    var yesterday;
    yesterday = +moment().subtract('days', 1).toDate();
    user.set('lastCron', yesterday);
    return window.location.reload();
  };
  appExports.emulateTenDays = function() {
    var yesterday;
    yesterday = +moment().subtract('days', 10).toDate();
    user.set('lastCron', yesterday);
    return window.location.reload();
  };
  return appExports.cheat = function() {
    user.incr('stats.exp', algos.tnl(user.get('stats.lvl')));
    return user.incr('stats.gp', 1000);
  };
};
