// Generated by CoffeeScript 1.4.0
var i18n;

i18n = require('derby-i18n');

i18n.plurals.add('he', function(n) {
  return n;
});

i18n.plurals.add('bg', function(n) {
  return n;
});

i18n.plurals.add('nl', function(n) {
  return n;
});

module.exports = i18n;
